secure: "wRaVOmZKVwREJQolDWvccFNuX/xt5WudH3zC2Xeve1TWATbTz+845OD7w+ukWrqEhtkKIy7jQ9Bf5pBvIQin4WuJQ0ELvktIj8N28bhfqoF6ng/OkGEyWA1rfuofQ7T38JdaWuGCxK+AUUiIcQEB6hdCw6y69IXHRvZ6g/3Z+le4XckNd+5OYkAyjHuwGyaPBJJf9pKaCXeopIT28JdEdqtQhgcpd2NZ64GoI4CGJ7A9wLRO3x66KYk/Ves0XzSw+uJJmHBnz5nIZZhEXdYkgZ/gCsRLSNJSQhkfW/lcFHmDj6g1prA4lQ8nsu8m5hdpIzR8eZ8dEWjOKEtHL2ZA9U12+gQIPxNSXvoOFSw8Bv9hTpxRWpp47uQPMjHWm+STUSEAEjy0IcrNfLNIN6ebHtRQ+DA1wRgHCGVrNeHq1wzCPgSZoNfBHYmJuu+dEALFHyPADHkA7zNYnMy9TCj//oE5n9kLcdMWKKDuJepxH+9gE7HJ/bYZZVztZ60GcviDgsjZ0vafxZ7Kr1iMcV3qEKnseqXWe6uveS9Q4/rJaRtQ/Ja5w0GmXr3CEkGono06qoHq4MxucKi35BDITZ9CukVJyfVny9cmWfkOtKQyIZWnlkz1CjQSa+h30CnZi3at0zkgxNvysNyRazR+vxvKeRK7F2eI2mmR/7A1jvJU2zg="

language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
